default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: genderator_development

test:
  <<: *default
  database: genderator_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
